# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named Flare_Blank_TemplateExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from Flare_Blank_TemplateExt import *
except ImportError:
    pass

def getPluginID():
    return "natron.community.plugins.FlareBlank"

def getLabel():
    return "Flare_Blank_Template"

def getVersion():
    return 1

def getIconPath():
    return "flareicon.png"

def getGrouping():
    return "Community/Draw/Lens Flare"

def getPluginDescription():
    return "A blank flare template to create new flares and presets"

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)

    # Create the user parameters
    lastNode.controller = lastNode.createPageParam("controller", "Controller")
    param = lastNode.createDouble2DParam("mouseXY", "Position XY")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setMinimum(-2147483648, 1)
    param.setMaximum(2147483647, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(377, 0)
    param.setValue(859, 1)
    param.setUsePointInteract(True)
    lastNode.mouseXY = param
    del param

    param = lastNode.createDouble2DParam("TrackPositionXY", "Track Position")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setMinimum(-2147483648, 1)
    param.setMaximum(2147483647, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.TrackPositionXY = param
    del param

    param = lastNode.createDouble2DParam("TrackLinkXY", "Track Link")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setMinimum(-2147483648, 1)
    param.setMaximum(2147483647, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(377, 0)
    param.setValue(859, 1)
    param.setVisibleByDefault(False)
    lastNode.TrackLinkXY = param
    del param

    param = lastNode.createDoubleParam("ROOT_GLOBALparamValueFloat0", "Global Scale")
    param.setMinimum(0, 0)
    param.setMaximum(30, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(30, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ROOT_GLOBALparamValueFloat0 = param
    del param

    param = lastNode.createDoubleParam("ROOT_GLOBALparamValueFloat1", "Global Rotation")
    param.setMinimum(0, 0)
    param.setMaximum(359.9999999999999, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(359.9999999999999, 0)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ROOT_GLOBALparamValueFloat1 = param
    del param

    param = lastNode.createDoubleParam("ROOT_GLOBALparamValueFloat2", "Evolution")
    param.setMinimum(1, 0)
    param.setMaximum(359.9999999999999, 0)
    param.setDisplayMinimum(1, 0)
    param.setDisplayMaximum(359.9999999999999, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("Value of the parameter.")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ROOT_GLOBALparamValueFloat2 = param
    del param

    param = lastNode.createColorParam("ROOT_GLOBALparamValueVec32", "Global Tint", False)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)
    param.setDefaultValue(1, 2)
    param.restoreDefaultValue(2)

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ROOT_GLOBALparamValueVec32 = param
    del param

    param = lastNode.createBooleanParam("ifparallel", "Parallel Flare")

    # Add the param to the page
    lastNode.controller.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.ifparallel = param
    del param

    lastNode.credit = lastNode.createPageParam("credit", "credit")
    param = lastNode.createStringParam("dev", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("Blank Flare Template Developed by")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.credit.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.dev = param
    del param

    param = lastNode.createStringParam("name", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("Fahad Hasan Pathik (CGVIRUS)")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.credit.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.name = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['controller', 'Settings', 'Node', 'credit'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "BG_Black"
    lastNode = app.createNode("net.sf.openfx.ConstantPlugin", 1, group)
    lastNode.setScriptName("BG_Black")
    lastNode.setLabel("BG Black")
    lastNode.setPosition(184, 67)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupBG_Black = lastNode

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    del lastNode
    # End of node "BG_Black"

    # Start of node "Grit_Texture_Input"
    lastNode = app.createNode("fr.inria.built-in.Input", 1, group)
    lastNode.setScriptName("Grit_Texture_Input")
    lastNode.setLabel("Grit Texture Input")
    lastNode.setPosition(-142, 547)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupGrit_Texture_Input = lastNode

    del lastNode
    # End of node "Grit_Texture_Input"

    # Start of node "Last_Node"
    lastNode = app.createNode("net.sf.openfx.Shadertoy", 1, group)
    lastNode.setScriptName("Last_Node")
    lastNode.setLabel("Last Node")
    lastNode.setPosition(1301, 755)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupLast_Node = lastNode

    param = lastNode.getParam("mousePosition")
    if param is not None:
        param.setValue(377, 0)
        param.setValue(859, 1)
        del param

    param = lastNode.getParam("paramValueFloat0")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramValueVec30")
    if param is not None:
        param.setValue(1, 0)
        param.setValue(1, 1)
        param.setValue(1, 2)
        del param

    param = lastNode.getParam("paramValueInt1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramValueFloat2")
    if param is not None:
        param.setValue(40, 0)
        del param

    param = lastNode.getParam("paramValueFloat3")
    if param is not None:
        param.setValue(0.4, 0)
        del param

    param = lastNode.getParam("paramValueFloat4")
    if param is not None:
        param.setValue(0.2, 0)
        del param

    param = lastNode.getParam("paramValueVec36")
    if param is not None:
        param.setValue(1, 0)
        param.setValue(1, 1)
        param.setValue(1, 2)
        del param

    param = lastNode.getParam("imageShaderFileName")
    if param is not None:
        param.setValue("/home/production/Code_PRojects/Natron Shadertoy/GLSL_Lense_Flare_Elements/Last_Node.frag.glsl")
        del param

    param = lastNode.getParam("imageShaderSource")
    if param is not None:
        param.setValue("// iChannel0: Link GLSL Elements, filter=linear, wrap=clamp\n// BBox: iChannel0\n\n/*\nImplementation and Development by CGVIRUS under GNU GPL Version 3 Licence.\nSome math ideas have derived from some genius minded folks and books.\nFeel free to share the knowledge and any type of code contribution is encouraged.\n*/\n\n\n//parametres\nuniform vec3 globaltint = vec3(1.0,1.0,1.0); // Global Tint\nuniform int isparalax= 0; // Parallel Flare, min=0, max=1\n\n\nvoid mainImage( out vec4 fragColor, in vec2 fragCoord )\n{\n    \n\tvec2 uv = fragCoord.xy / iResolution.xy - 0.5;\n\tuv.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\tvec3 mouse = vec3(iMouse.xy/iResolution.xy - 0.5,iMouse.z-.5);\n\tmouse.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\t\n    vec2 xy = fragCoord.xy / iResolution.xy;\n    \n    vec2 fxy = vec2 (1.0 - xy.x,1.0 - xy.y); //flipped\n    \n    vec4 linker = texture(iChannel0,xy);\n    vec4 linkerflip = texture(iChannel0,fxy);\n    \n\tif (isparalax == 1){\n\tfragColor = (linkerflip+linker)*vec4(globaltint,1.0);\n\t}\n\telse{\n\tfragColor = linker*vec4(globaltint,1.0);\n\t}\n}\n")
        del param

    param = lastNode.getParam("mipmap0")
    if param is not None:
        param.set("linear")
        del param

    param = lastNode.getParam("wrap0")
    if param is not None:
        param.set("clamp")
        del param

    param = lastNode.getParam("inputLabel0")
    if param is not None:
        param.setValue("Link GLSL Elements")
        del param

    param = lastNode.getParam("inputEnable1")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("inputEnable2")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("inputEnable3")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("bbox")
    if param is not None:
        param.set("iChannel0")
        del param

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    param = lastNode.getParam("mouseParams")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("paramCount")
    if param is not None:
        param.setValue(2, 0)
        del param

    param = lastNode.getParam("paramType0")
    if param is not None:
        param.set("vec3")
        del param

    param = lastNode.getParam("paramName0")
    if param is not None:
        param.setValue("globaltint")
        del param

    param = lastNode.getParam("paramLabel0")
    if param is not None:
        param.setValue("Global Tint")
        del param

    param = lastNode.getParam("paramDefaultVec30")
    if param is not None:
        param.setValue(1, 0)
        param.setValue(1, 1)
        param.setValue(1, 2)
        del param

    param = lastNode.getParam("paramType1")
    if param is not None:
        param.set("int")
        del param

    param = lastNode.getParam("paramName1")
    if param is not None:
        param.setValue("isparalax")
        del param

    param = lastNode.getParam("paramLabel1")
    if param is not None:
        param.setValue("Parallel Flare")
        del param

    param = lastNode.getParam("paramMinInt1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxInt1")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramType2")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName2")
    if param is not None:
        param.setValue("coresize")
        del param

    param = lastNode.getParam("paramLabel2")
    if param is not None:
        param.setValue("Thresold")
        del param

    param = lastNode.getParam("paramType3")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName3")
    if param is not None:
        param.setValue("threshold")
        del param

    param = lastNode.getParam("paramLabel3")
    if param is not None:
        param.setValue("Brightness")
        del param

    param = lastNode.getParam("paramType4")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName4")
    if param is not None:
        param.setValue("raydepth")
        del param

    param = lastNode.getParam("paramLabel4")
    if param is not None:
        param.setValue("Ray depth")
        del param

    param = lastNode.getParam("paramType5")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName5")
    if param is not None:
        param.setValue("rotation")
        del param

    param = lastNode.getParam("paramLabel5")
    if param is not None:
        param.setValue("Rotation")
        del param

    param = lastNode.getParam("paramType6")
    if param is not None:
        param.set("vec3")
        del param

    param = lastNode.getParam("paramName6")
    if param is not None:
        param.setValue("SunColor")
        del param

    param = lastNode.getParam("paramLabel6")
    if param is not None:
        param.setValue("Sun Color")
        del param

    del lastNode
    # End of node "Last_Node"

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setLabel("Output1")
    lastNode.setPosition(1301, 945)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "Sun_2"
    lastNode = app.createNode("net.sf.openfx.Shadertoy", 1, group)
    lastNode.setScriptName("Sun_2")
    lastNode.setLabel("Grit")
    lastNode.setPosition(184, 488)
    lastNode.setSize(104, 32)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupSun_2 = lastNode

    param = lastNode.getParam("mousePosition")
    if param is not None:
        param.setValueAtTime(420, 1, 0)
        param.setValueAtTime(772, 1, 1)
        del param

    param = lastNode.getParam("mouseClick")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("mousePressed")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueBool0")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt0")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat0")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramValueVec20")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec30")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec40")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool1")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt1")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramValueVec21")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec31")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec41")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool2")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt2")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramValueVec22")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec32")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec42")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool3")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt3")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat3")
    if param is not None:
        param.setValueAtTime(40, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec23")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec33")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec43")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool4")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt4")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat4")
    if param is not None:
        param.setValueAtTime(0.4, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec24")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec34")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec44")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool5")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt5")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat5")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec25")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec35")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec45")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool6")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt6")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat6")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec26")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec36")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        param.setValueAtTime(1, 1, 1)
        param.setValueAtTime(1, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec46")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool7")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt7")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat7")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec27")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec37")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec47")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool8")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt8")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat8")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec28")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec38")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec48")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool9")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt9")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat9")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec29")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec39")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec49")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool10")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt10")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat10")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec210")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec310")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec410")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool11")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt11")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat11")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec211")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec311")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec411")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool12")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt12")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat12")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec212")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec312")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec412")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool13")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt13")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat13")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec213")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec313")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec413")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool14")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt14")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat14")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec214")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec314")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec414")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool15")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt15")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat15")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec215")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec315")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec415")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool16")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt16")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat16")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec216")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec316")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec416")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool17")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt17")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat17")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec217")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec317")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec417")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool18")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt18")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat18")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec218")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec318")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec418")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool19")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt19")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat19")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec219")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec319")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec419")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("imageShaderPreset")
    if param is not None:
        param.set("Lens Flare Elements/Grit_Mask")
        del param

    param = lastNode.getParam("imageShaderSource")
    if param is not None:
        param.setValue("// iChannel1: Grit Texture Source, filter=linear, wrap=repeat\n// BBox: iChannel1\n// iChannel0: Link GLSL Elements, filter=linear, wrap=clamp\n// BBox: iChannel0\n\n// Grit_Mask.frag\n/*\nImplementation and Development by CGVIRUS under GNU GPL Version 3 Licence.\nSome math ideas have derived from some genius minded folks and books.\nFeel free to share the knowledge and any type of code contribution is encouraged.\n*/\n\n\n//Global parametres\nuniform float globalSize = 1.0; // Global Scale, min=0., max=100.\nuniform float globalRotate= 0.0; // Global Rotation, min=0., max=360.\nuniform float evolution= 1.0; // Evolution, min=1.0, max=360.\n\n//parametres\nuniform float coresize = 40.0; // Thresold , min=0.1, max=100.\nuniform float threshold = .4; // Brightness , min=0., max=1..\n\n\n//Cretes a circular Grit MAsk\nfloat grit(vec2 uv, vec2 pos, float size)\n{\n    \n    float rot = radians(globalRotate)*evolution;\n    mat2 m = mat2(cos(rot), -sin(rot), sin(rot), cos(rot));\n    uv  = m*uv;\n    pos = m*pos;\n    \n    vec2 main = uv-pos;\n\t\n\tfloat ang = atan(main.y, main.x);\n\tfloat dist=length(main); dist = pow(dist,.1);\n\t\n\tfloat f0 = (threshold*globalSize)/(length(uv-pos)*(1.0/size*100)/coresize);\n    \n    return f0;\n}\n\n\nvoid mainImage( out vec4 fragColor, in vec2 fragCoord )\n{\n    \n\tvec2 uv = fragCoord.xy / iResolution.xy - 0.5;\n\tuv.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\tvec3 mouse = vec3(iMouse.xy/iResolution.xy - 0.5,iMouse.z-.5);\n\tmouse.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\tfloat c = grit(uv,mouse.xy,1.);\n\t\n    vec2 xy = fragCoord.xy / iResolution.xy;\n    vec4 linker = texture(iChannel0,xy);\n    vec4 gritTex = texture(iChannel1,xy);\n\t\n\tfragColor = vec4(vec3(c),1.0)*gritTex+linker;\n}\n")
        del param

    param = lastNode.getParam("mipmap0")
    if param is not None:
        param.set("linear")
        del param

    param = lastNode.getParam("wrap0")
    if param is not None:
        param.set("clamp")
        del param

    param = lastNode.getParam("inputLabel0")
    if param is not None:
        param.setValue("Link GLSL Elements")
        del param

    param = lastNode.getParam("mipmap1")
    if param is not None:
        param.set("linear")
        del param

    param = lastNode.getParam("inputLabel1")
    if param is not None:
        param.setValue("Grit Texture Source")
        del param

    param = lastNode.getParam("inputEnable2")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("inputEnable3")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("bbox")
    if param is not None:
        param.setValueAtTime(5, 1)
        del param

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    param = lastNode.getParam("NatronParamFormatSize")
    if param is not None:
        param.setValueAtTime(640, 1, 0)
        param.setValueAtTime(480, 1, 1)
        del param

    param = lastNode.getParam("NatronParamFormatPar")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        del param

    param = lastNode.getParam("startDate")
    if param is not None:
        param.setValueAtTime(1970, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(1, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramCount")
    if param is not None:
        param.setValue(5, 0)
        del param

    param = lastNode.getParam("paramType0")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName0")
    if param is not None:
        param.setValue("globalSize")
        del param

    param = lastNode.getParam("paramLabel0")
    if param is not None:
        param.setValue("Global Scale")
        del param

    param = lastNode.getParam("paramDefaultFloat0")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMinFloat0")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat0")
    if param is not None:
        param.setValue(99.99999999999999, 0)
        del param

    param = lastNode.getParam("paramType1")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName1")
    if param is not None:
        param.setValue("globalRotate")
        del param

    param = lastNode.getParam("paramLabel1")
    if param is not None:
        param.setValue("Global Rotation")
        del param

    param = lastNode.getParam("paramMinFloat1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat1")
    if param is not None:
        param.setValue(359.9999999999999, 0)
        del param

    param = lastNode.getParam("paramType2")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName2")
    if param is not None:
        param.setValue("evolution")
        del param

    param = lastNode.getParam("paramLabel2")
    if param is not None:
        param.setValue("Evolution")
        del param

    param = lastNode.getParam("paramDefaultFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMinFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMaxFloat2")
    if param is not None:
        param.setValue(359.9999999999999, 0)
        del param

    param = lastNode.getParam("paramType3")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName3")
    if param is not None:
        param.setValue("coresize")
        del param

    param = lastNode.getParam("paramLabel3")
    if param is not None:
        param.setValue("Thresold")
        del param

    param = lastNode.getParam("paramDefaultFloat3")
    if param is not None:
        param.setValue(40, 0)
        del param

    param = lastNode.getParam("paramMinFloat3")
    if param is not None:
        param.setValue(0.09999999999999999, 0)
        del param

    param = lastNode.getParam("paramMaxFloat3")
    if param is not None:
        param.setValue(99.99999999999999, 0)
        del param

    param = lastNode.getParam("paramType4")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName4")
    if param is not None:
        param.setValue("threshold")
        del param

    param = lastNode.getParam("paramLabel4")
    if param is not None:
        param.setValue("Brightness")
        del param

    param = lastNode.getParam("paramDefaultFloat4")
    if param is not None:
        param.setValue(0.4, 0)
        del param

    param = lastNode.getParam("paramMinFloat4")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat4")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramType5")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName5")
    if param is not None:
        param.setValue("rotation")
        del param

    param = lastNode.getParam("paramLabel5")
    if param is not None:
        param.setValue("Rotation")
        del param

    param = lastNode.getParam("paramType6")
    if param is not None:
        param.set("vec3")
        del param

    param = lastNode.getParam("paramName6")
    if param is not None:
        param.setValue("SunColor")
        del param

    param = lastNode.getParam("paramLabel6")
    if param is not None:
        param.setValue("Sun Color")
        del param

    del lastNode
    # End of node "Sun_2"

    # Start of node "Sun_2_2"
    lastNode = app.createNode("net.sf.openfx.Shadertoy", 1, group)
    lastNode.setScriptName("Sun_2_2")
    lastNode.setLabel("Sun")
    lastNode.setPosition(184, 129)
    lastNode.setSize(104, 32)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupSun_2_2 = lastNode

    param = lastNode.getParam("mousePosition")
    if param is not None:
        param.setValueAtTime(420, 1, 0)
        param.setValueAtTime(772, 1, 1)
        del param

    param = lastNode.getParam("mouseClick")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("mousePressed")
    if param is not None:
        param.setValueAtTime(True, 1)
        del param

    param = lastNode.getParam("paramValueBool0")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt0")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat0")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramValueVec20")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec30")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec40")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool1")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt1")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramValueVec21")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec31")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec41")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool2")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt2")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramValueVec22")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec32")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec42")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool3")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt3")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat3")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec23")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec33")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec43")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool4")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt4")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat4")
    if param is not None:
        param.setValueAtTime(0.2, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec24")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec34")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec44")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool5")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt5")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat5")
    if param is not None:
        param.setValueAtTime(0.2, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec25")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec35")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec45")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool6")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt6")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat6")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec26")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec36")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        param.setValueAtTime(1, 1, 1)
        param.setValueAtTime(1, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec46")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool7")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt7")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat7")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec27")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec37")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        param.setValueAtTime(1, 1, 1)
        param.setValueAtTime(1, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec47")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool8")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt8")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat8")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec28")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec38")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec48")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool9")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt9")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat9")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec29")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec39")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec49")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool10")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt10")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat10")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec210")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec310")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec410")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool11")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt11")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat11")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec211")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec311")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec411")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool12")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt12")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat12")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec212")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec312")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec412")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool13")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt13")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat13")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec213")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec313")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec413")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool14")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt14")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat14")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec214")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec314")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec414")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool15")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt15")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat15")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec215")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec315")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec415")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool16")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt16")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat16")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec216")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec316")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec416")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool17")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt17")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat17")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec217")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec317")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec417")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool18")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt18")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat18")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec218")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec318")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec418")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramValueBool19")
    if param is not None:
        param.setValueAtTime(False, 1)
        del param

    param = lastNode.getParam("paramValueInt19")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueFloat19")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        del param

    param = lastNode.getParam("paramValueVec219")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        del param

    param = lastNode.getParam("paramValueVec319")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        del param

    param = lastNode.getParam("paramValueVec419")
    if param is not None:
        param.setValueAtTime(0, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(0, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("imageShaderPreset")
    if param is not None:
        param.set("Lens Flare Elements/sun")
        del param

    param = lastNode.getParam("imageShaderSource")
    if param is not None:
        param.setValue("// iChannel0: Link GLSL Elements, filter=linear, wrap=clamp\n// BBox: iChannel0\n\n// sun.frag\n/*\nImplementation and Development by CGVIRUS under GNU GPL Version 3 Licence.\nSome base math ideas derived from Musk\'s Flare https://www.shadertoy.com/view/4sX3Rs\nSome math ideas also have derived from some genius minded folks and books.\nFeel free to share the knowledge and any type of code contribution is encouraged.\n*/\n\n\n//Global parametres\nuniform float globalSize = 1.0; // Global Scale, min=0., max=100.\nuniform float globalRotate= 0.0; // Global Rotation, min=0., max=360.\nuniform float evolution= 1.0; // Evolution, min=1.0, max=360.\n\n//parametres\nuniform float coresize = 2.; // Sun Core Size , min=0., max=100.\nuniform int raycount = 0; // Ray Count , min=0., max=100.\nuniform float raydepth = .2; // Ray depth , min=-1.5, max=1.5\nuniform float rotation = .0; // Rotation , min=0.,max=360.\nuniform vec3 SunColor = vec3(1.,1.,1.); // Sun Color\n\n\n//Procedural Sun Generation\nfloat sun(vec2 uv, vec2 pos, float size)\n{\n    float rot = radians(rotation+globalRotate)*evolution;\n    mat2 m = mat2(cos(rot), -sin(rot), sin(rot), cos(rot));\n    uv  = m*uv;\n    pos = m*pos;\n    \n    vec2 vector = uv-pos;\n\t\n\tfloat angle = atan(vector.y, vector.x);\n\tfloat dist=length(vector); dist = pow(dist,.1);\n\t\n\tfloat f0 = 1.0/(length(uv-pos)*(1.0/size*100)/(coresize*globalSize));\n\t\n    \n    return f0+f0*(sin((angle)*raycount)*raydepth+dist*.1+.9);\n}\n\n\nvoid mainImage( out vec4 fragColor, in vec2 fragCoord )\n{\n    \n\tvec2 uv = fragCoord.xy / iResolution.xy - 0.5;\n\tuv.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\tvec3 mouse = vec3(iMouse.xy/iResolution.xy - 0.5,iMouse.z-.5);\n\tmouse.x *= iResolution.x/iResolution.y; //fix aspect ratio\n\tfloat c = sun(uv,mouse.xy,1.);\n\t\n    vec2 xy = fragCoord.xy / iResolution.xy;\n    vec4 linker = texture(iChannel0,xy);\n\t\n\tfragColor = vec4(c*SunColor,1.0)+linker;\n}\n")
        del param

    param = lastNode.getParam("mipmap0")
    if param is not None:
        param.set("linear")
        del param

    param = lastNode.getParam("wrap0")
    if param is not None:
        param.set("clamp")
        del param

    param = lastNode.getParam("inputLabel0")
    if param is not None:
        param.setValue("Link GLSL Elements")
        del param

    param = lastNode.getParam("inputEnable1")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("inputEnable2")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("inputEnable3")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("bbox")
    if param is not None:
        param.setValueAtTime(4, 1)
        del param

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    param = lastNode.getParam("NatronParamFormatSize")
    if param is not None:
        param.setValueAtTime(640, 1, 0)
        param.setValueAtTime(480, 1, 1)
        del param

    param = lastNode.getParam("NatronParamFormatPar")
    if param is not None:
        param.setValueAtTime(1, 1, 0)
        del param

    param = lastNode.getParam("startDate")
    if param is not None:
        param.setValueAtTime(1970, 1, 0)
        param.setValueAtTime(0, 1, 1)
        param.setValueAtTime(1, 1, 2)
        param.setValueAtTime(0, 1, 3)
        del param

    param = lastNode.getParam("paramCount")
    if param is not None:
        param.setValue(8, 0)
        del param

    param = lastNode.getParam("paramType0")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName0")
    if param is not None:
        param.setValue("globalSize")
        del param

    param = lastNode.getParam("paramLabel0")
    if param is not None:
        param.setValue("Global Scale")
        del param

    param = lastNode.getParam("paramDefaultFloat0")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMinFloat0")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat0")
    if param is not None:
        param.setValue(99.99999999999999, 0)
        del param

    param = lastNode.getParam("paramType1")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName1")
    if param is not None:
        param.setValue("globalRotate")
        del param

    param = lastNode.getParam("paramLabel1")
    if param is not None:
        param.setValue("Global Rotation")
        del param

    param = lastNode.getParam("paramMinFloat1")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat1")
    if param is not None:
        param.setValue(359.9999999999999, 0)
        del param

    param = lastNode.getParam("paramType2")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName2")
    if param is not None:
        param.setValue("evolution")
        del param

    param = lastNode.getParam("paramLabel2")
    if param is not None:
        param.setValue("Evolution")
        del param

    param = lastNode.getParam("paramDefaultFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMinFloat2")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("paramMaxFloat2")
    if param is not None:
        param.setValue(359.9999999999999, 0)
        del param

    param = lastNode.getParam("paramType3")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName3")
    if param is not None:
        param.setValue("coresize")
        del param

    param = lastNode.getParam("paramLabel3")
    if param is not None:
        param.setValue("Sun Core Size")
        del param

    param = lastNode.getParam("paramDefaultFloat3")
    if param is not None:
        param.setValue(2, 0)
        del param

    param = lastNode.getParam("paramMinFloat3")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat3")
    if param is not None:
        param.setValue(99.99999999999999, 0)
        del param

    param = lastNode.getParam("paramType4")
    if param is not None:
        param.set("int")
        del param

    param = lastNode.getParam("paramName4")
    if param is not None:
        param.setValue("raycount")
        del param

    param = lastNode.getParam("paramLabel4")
    if param is not None:
        param.setValue("Ray Count")
        del param

    param = lastNode.getParam("paramMinInt4")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxInt4")
    if param is not None:
        param.setValue(100, 0)
        del param

    param = lastNode.getParam("paramType5")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName5")
    if param is not None:
        param.setValue("raydepth")
        del param

    param = lastNode.getParam("paramLabel5")
    if param is not None:
        param.setValue("Ray depth")
        del param

    param = lastNode.getParam("paramDefaultFloat5")
    if param is not None:
        param.setValue(0.2, 0)
        del param

    param = lastNode.getParam("paramMinFloat5")
    if param is not None:
        param.setValue(-1.5, 0)
        del param

    param = lastNode.getParam("paramMaxFloat5")
    if param is not None:
        param.setValue(1.5, 0)
        del param

    param = lastNode.getParam("paramType6")
    if param is not None:
        param.set("float")
        del param

    param = lastNode.getParam("paramName6")
    if param is not None:
        param.setValue("rotation")
        del param

    param = lastNode.getParam("paramLabel6")
    if param is not None:
        param.setValue("Rotation")
        del param

    param = lastNode.getParam("paramMinFloat6")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("paramMaxFloat6")
    if param is not None:
        param.setValue(359.9999999999999, 0)
        del param

    param = lastNode.getParam("paramType7")
    if param is not None:
        param.set("vec3")
        del param

    param = lastNode.getParam("paramName7")
    if param is not None:
        param.setValue("SunColor")
        del param

    param = lastNode.getParam("paramLabel7")
    if param is not None:
        param.setValue("Sun Color")
        del param

    param = lastNode.getParam("paramDefaultVec37")
    if param is not None:
        param.setValue(1, 0)
        param.setValue(1, 1)
        param.setValue(1, 2)
        del param

    del lastNode
    # End of node "Sun_2_2"

    # Start of node "All_Flare_Modules_Here"
    lastNode = app.createNode("fr.inria.built-in.BackDrop", 1, group)
    lastNode.setScriptName("All_Flare_Modules_Here")
    lastNode.setLabel("All Flare Modules Here")
    lastNode.setPosition(16, -22)
    lastNode.setSize(652, 659)
    lastNode.setColor(0.451, 0.3569, 0.1882)
    groupAll_Flare_Modules_Here = lastNode

    param = lastNode.getParam("Label")
    if param is not None:
        param.setValue("<font size=\"6\" color=\"#000000\" face=\"Droid Sans\">Copy Nodes>Link And Create Your Flare!</font>")
        del param

    del lastNode
    # End of node "All_Flare_Modules_Here"

    # Start of node "Dot1"
    lastNode = app.createNode("fr.inria.built-in.Dot", 1, group)
    lastNode.setScriptName("Dot1")
    lastNode.setLabel("Dot1")
    lastNode.setPosition(1174, 770)
    lastNode.setSize(15, 15)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupDot1 = lastNode

    del lastNode
    # End of node "Dot1"

    # Start of node "Clamp1"
    lastNode = app.createNode("net.sf.openfx.Clamp", 2, group)
    lastNode.setScriptName("Clamp1")
    lastNode.setLabel("Clamp1")
    lastNode.setPosition(1301, 850)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.48, 0.66, 1)
    groupClamp1 = lastNode

    param = lastNode.getParam("minClampToEnable")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("maxClampToEnable")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("premult")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "Clamp1"

    # Start of node "Switch1"
    lastNode = app.createNode("net.sf.openfx.switchPlugin", 1, group)
    lastNode.setScriptName("Switch1")
    lastNode.setLabel("Switch1")
    lastNode.setPosition(38, 488)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.3, 0.37, 0.776)
    groupSwitch1 = lastNode

    param = lastNode.getParam("which")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("automatic")
    if param is not None:
        param.setValueAtTime(True, 0)
        del param

    del lastNode
    # End of node "Switch1"

    # Start of node "Constant1"
    lastNode = app.createNode("net.sf.openfx.ConstantPlugin", 1, group)
    lastNode.setScriptName("Constant1")
    lastNode.setLabel("Constant1")
    lastNode.setPosition(-145, 488)
    lastNode.setSize(104, 31)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupConstant1 = lastNode

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    del lastNode
    # End of node "Constant1"

    # Now that all nodes are created we can connect them together, restore expressions
    groupLast_Node.connectInput(0, groupDot1)
    groupOutput1.connectInput(0, groupClamp1)
    groupSun_2.connectInput(0, groupSun_2_2)
    groupSun_2.connectInput(1, groupSwitch1)
    groupSun_2_2.connectInput(0, groupBG_Black)
    groupDot1.connectInput(0, groupSun_2)
    groupClamp1.connectInput(0, groupLast_Node)
    groupSwitch1.connectInput(0, groupGrit_Texture_Input)
    groupSwitch1.connectInput(1, groupConstant1)

    param = groupLast_Node.getParam("mousePosition")
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 0)
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 1)
    del param
    param = groupLast_Node.getParam("paramValueVec30")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueVec32"), 0, 0)
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueVec32"), 1, 1)
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueVec32"), 2, 2)
    del param
    param = groupLast_Node.getParam("paramValueInt1")
    param.setExpression("thisGroup.ifparallel.get()", False, 0)
    del param
    param = groupSun_2.getParam("mousePosition")
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 0)
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 1)
    del param
    param = groupSun_2.getParam("paramValueFloat0")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat0"), 0, 0)
    del param
    param = groupSun_2.getParam("paramValueFloat1")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat1"), 0, 0)
    del param
    param = groupSun_2.getParam("paramValueFloat2")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat2"), 0, 0)
    del param
    param = groupSun_2_2.getParam("mousePosition")
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 0)
    param.setExpression("thisGroup.TrackLinkXY.get()[dimension]", False, 1)
    del param
    param = groupSun_2_2.getParam("paramValueFloat0")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat0"), 0, 0)
    del param
    param = groupSun_2_2.getParam("paramValueFloat1")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat1"), 0, 0)
    del param
    param = groupSun_2_2.getParam("paramValueFloat2")
    param.slaveTo(group.getParam("ROOT_GLOBALparamValueFloat2"), 0, 0)
    del param

    param = group.getParam("TrackLinkXY")
    param.setExpression("thisNode.mouseXY.get()[dimension] + thisNode.TrackPositionXY.get()[dimension]", False, 0)
    param.setExpression("thisNode.mouseXY.get()[dimension] + thisNode.TrackPositionXY.get()[dimension]", False, 1)
    del param
    try:
        extModule = sys.modules["Flare_Blank_TemplateExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
